defaults:
  - _self_
  - model: node
  - dataset: bouncingball
  - training: forecast_forecast

hydra:
  output_subdir: null
  run:
    dir: .

# Random seed of the run
seed: 125125125
devices: [0]

# Experiment folder naming
expname: ${dataset.dataset}_${model.model_type}_${training.z_amort_train}ztrain_${training.z_amort_test}ztest_${training.num_steps}iterations_${seed}seed
model_path: ""
checkpt: ""

# For training, overrideable by cmd
train: true
resume: false
